// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../../../../../io/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function AddNote(text, book, chapter, verse) {
    return $Call.ByID(1300526171, text, book, chapter, verse);
}

/**
 * @param {number} id
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id, text, book, chapter, verse) {
    return $Call.ByID(1333091635, id, text, book, chapter, verse);
}

/**
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetAllNotes() {
    return $Call.ByID(1933638692).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNoteByID(id) {
    return $Call.ByID(3084527864, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNoteByVerse(book, chapter, verse) {
    return $Call.ByID(7815210, book, chapter, verse).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNotesByBook(book) {
    return $Call.ByID(3831799373, book).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @param {number} chapter
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNotesByChapter(book, chapter) {
    return $Call.ByID(1620855149, book, chapter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {io$0.Reader | null} f
 * @returns {$CancellablePromise<void>}
 */
export function Import(f) {
    return $Call.ByID(4004692085, f);
}

/**
 * @param {number} id
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function UpdateNote(id, text, book, chapter, verse) {
    return $Call.ByID(657279265, id, text, book, chapter, verse);
}

// Private type creation functions
const $$createType0 = $models.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
