// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Note represents user-generated study content or commentary.
 */
export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("verse_ref" in $$source)) {
            /**
             * @member
             * @type {VerseKey}
             */
            this["verse_ref"] = (new VerseKey());
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * Supports Markdown or HTML string from Vue
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * Unix timestamp for easy frontend formatting
             * @member
             * @type {time$0.Time | null}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["deleted_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("verse_ref" in $$parsedSource) {
            $$parsedSource["verse_ref"] = $$createField1_0($$parsedSource["verse_ref"]);
        }
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}

/**
 * VerseKey acts as a unique, lightweight identifier for any verse in the Bible.
 * This is incredibly useful for map lookups and frontend routing.
 */
export class VerseKey {
    /**
     * Creates a new VerseKey instance.
     * @param {Partial<VerseKey>} [$$source = {}] - The source object to create the VerseKey.
     */
    constructor($$source = {}) {
        if (!("book_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["book_id"] = 0;
        }
        if (!("chapter" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verse"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerseKey instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VerseKey}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VerseKey(/** @type {Partial<VerseKey>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = VerseKey.createFrom;
