// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function AddNote(text, book, chapter, verse) {
    return $Call.ByID(913750679, text, book, chapter, verse);
}

/**
 * @param {number} id
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id, text, book, chapter, verse) {
    return $Call.ByID(3620073671, id, text, book, chapter, verse);
}

/**
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetAllNotes() {
    return $Call.ByID(971743816).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetBooksOfTheBible() {
    return $Call.ByID(2449458788).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} book
 * @returns {$CancellablePromise<number>}
 */
export function GetCountOfChaptersInTheBook(book) {
    return $Call.ByID(2079381295, book);
}

/**
 * @param {string} book
 * @param {number} chapter
 * @returns {$CancellablePromise<number>}
 */
export function GetCountOfVersesInTheChapter(book, chapter) {
    return $Call.ByID(2023180287, book, chapter);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNoteByID(id) {
    return $Call.ByID(1957627908, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNoteByVerse(book, chapter, verse) {
    return $Call.ByID(902583246, book, chapter, verse).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNotesByBook(book) {
    return $Call.ByID(3294203401, book).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @param {number} chapter
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNotesByChapter(book, chapter) {
    return $Call.ByID(677043921, book, chapter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} version
 * @param {string} book
 * @param {number} chapter
 * @returns {$CancellablePromise<($models.GetVersesResponse | null)[]>}
 */
export function GetVerses(version, book, chapter) {
    return $Call.ByID(931891162, version, book, chapter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowNotification(title, message) {
    return $Call.ByID(1671713206, title, message);
}

/**
 * @param {number} id
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function UpdateNote(id, text, book, chapter, verse) {
    return $Call.ByID(3325951317, id, text, book, chapter, verse);
}

// Private type creation functions
const $$createType0 = $models.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.GetVersesResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
