// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BibleService from "./bibleservice.js";
export {
    BibleService
};

export {
    GetVersesResponse,
    Note,
    Verse1,
    VerseKey
} from "./models.js";
