// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function AddNote(text, book, chapter, verse) {
    return $Call.ByID(2777248012, text, book, chapter, verse);
}

/**
 * @param {number} id
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id, text, book, chapter, verse) {
    return $Call.ByID(347501482, id, text, book, chapter, verse);
}

/**
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetAllNotes() {
    return $Call.ByID(3702603387).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetBooksOfTheBible() {
    return $Call.ByID(2386403857).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} book
 * @returns {$CancellablePromise<number>}
 */
export function GetCountOfChaptersInTheBook(book) {
    return $Call.ByID(2981323392, book);
}

/**
 * @param {string} book
 * @param {number} chapter
 * @returns {$CancellablePromise<number>}
 */
export function GetCountOfVersesInTheChapter(book, chapter) {
    return $Call.ByID(3659933878, book, chapter);
}

/**
 * @param {string} book
 * @param {number} chapterNum
 * @param {number} verseNum
 * @returns {$CancellablePromise<$models.GetCrossReferencesResult | null>}
 */
export function GetCrossReferences(book, chapterNum, verseNum) {
    return $Call.ByID(3935083199, book, chapterNum, verseNum).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetListOfTranslationsAvailable() {
    return $Call.ByID(2514256885).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNoteByID(id) {
    return $Call.ByID(3458433867, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNoteByVerse(book, chapter, verse) {
    return $Call.ByID(3249457771, book, chapter, verse).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNotesByBook(book) {
    return $Call.ByID(4157881560, book).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} book
 * @param {number} chapter
 * @returns {$CancellablePromise<($models.Note | null)[]>}
 */
export function GetNotesByChapter(book, chapter) {
    return $Call.ByID(385003122, book, chapter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} version
 * @param {string} book
 * @param {number} chapter
 * @returns {$CancellablePromise<($models.GetVersesResponse | null)[]>}
 */
export function GetVerses(version, book, chapter) {
    return $Call.ByID(1005662017, version, book, chapter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowError(title, message) {
    return $Call.ByID(1729053622, title, message);
}

/**
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowWarning(title, message) {
    return $Call.ByID(219141692, title, message);
}

/**
 * @param {number} id
 * @param {string} text
 * @param {number} book
 * @param {number} chapter
 * @param {number} verse
 * @returns {$CancellablePromise<void>}
 */
export function UpdateNote(id, text, book, chapter, verse) {
    return $Call.ByID(259919972, id, text, book, chapter, verse);
}

// Private type creation functions
const $$createType0 = $models.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.GetCrossReferencesResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GetVersesResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
