// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class GetCrossReferencesResult {
    /**
     * Creates a new GetCrossReferencesResult instance.
     * @param {Partial<GetCrossReferencesResult>} [$$source = {}] - The source object to create the GetCrossReferencesResult.
     */
    constructor($$source = {}) {
        if (!("references" in $$source)) {
            /**
             * @member
             * @type {(Reference | null)[]}
             */
            this["references"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetCrossReferencesResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetCrossReferencesResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField0_0($$parsedSource["references"]);
        }
        return new GetCrossReferencesResult(/** @type {Partial<GetCrossReferencesResult>} */($$parsedSource));
    }
}

export class GetVersesResponse {
    /**
     * Creates a new GetVersesResponse instance.
     * @param {Partial<GetVersesResponse>} [$$source = {}] - The source object to create the GetVersesResponse.
     */
    constructor($$source = {}) {
        if (!("num" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["num"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetVersesResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetVersesResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetVersesResponse(/** @type {Partial<GetVersesResponse>} */($$parsedSource));
    }
}

/**
 * Note represents user-generated study content or commentary.
 */
export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("verse_ref" in $$source)) {
            /**
             * @member
             * @type {VerseKey}
             */
            this["verse_ref"] = (new VerseKey());
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * Supports Markdown or HTML string from Vue
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * Unix timestamp for easy frontend formatting
             * @member
             * @type {time$0.Time | null}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["deleted_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("verse_ref" in $$parsedSource) {
            $$parsedSource["verse_ref"] = $$createField1_0($$parsedSource["verse_ref"]);
        }
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}

export class Reference {
    /**
     * Creates a new Reference instance.
     * @param {Partial<Reference>} [$$source = {}] - The source object to create the Reference.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("from_book" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from_book"] = "";
        }
        if (!("from_chapter" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["from_chapter"] = 0;
        }
        if (!("from_verse" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["from_verse"] = 0;
        }
        if (!("to_book" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to_book"] = "";
        }
        if (!("to_chapter" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["to_chapter"] = 0;
        }
        if (!("to_verse_start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["to_verse_start"] = 0;
        }
        if (!("to_verse_end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["to_verse_end"] = 0;
        }
        if (!("votes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["votes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Reference instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Reference}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Reference(/** @type {Partial<Reference>} */($$parsedSource));
    }
}

/**
 * VerseKey acts as a unique, lightweight identifier for any verse in the Bible.
 * This is incredibly useful for map lookups and frontend routing.
 */
export class VerseKey {
    /**
     * Creates a new VerseKey instance.
     * @param {Partial<VerseKey>} [$$source = {}] - The source object to create the VerseKey.
     */
    constructor($$source = {}) {
        if (!("book_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["book_id"] = 0;
        }
        if (!("chapter" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verse"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerseKey instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VerseKey}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VerseKey(/** @type {Partial<VerseKey>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Reference.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = VerseKey.createFrom;
